services:
  k6-prom: &k6-prom
    build: .
    depends_on:
      - prometheus
      # - poetry-project
    volumes:
      - .:/app:delegated
    environment:
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    entrypoint: ["/bin/sh", "-c", "echo 'k6-prom is a template service and should not run'"]
  k6-simple:
    <<: *k6-prom
    entrypoint: k6
    command: run --vus 150 --duration 30s -o xk6-prometheus-rw /app/simple_tests/basic_k6_test.js
  # # a machine with k6 environment stays alive
  # k6-infinite:
  #   <<: *k6-prom
  #   entrypoint: ["tail", "-f", "/dev/null"]

  # # to-be-tested service
  # poetry-project:
  #   container_name: poetry-project
  #   build: ./poetry-fastapi-docker
  #   ports:
  #     - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - grafana
    ports:
      - 9000:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data-storage:/var/lib/grafana
    ports:
      - 4000:4000
    environment:
      - GF_SERVER_HTTP_PORT=4000

volumes:
  prometheus-data:
  grafana-data-storage: